// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clothes": {
            "get": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Получает список доступной одежды",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clothes"
                ],
                "summary": "Получить список одежды",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/clothes.ClotheUserResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clothes/buy/{id}": {
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Покупает предмет одежды",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clothes"
                ],
                "summary": "Купить предмет одежды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета одежды",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/clothes.ClotheUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clothes/equip/{id}": {
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Экипирует предмет одежды",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clothes"
                ],
                "summary": "Экипировать предмет одежды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета одежды",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/clothes.ClotheUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clothes/{id}": {
            "get": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Получает информацию о конкретном предмете одежды",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clothes"
                ],
                "summary": "Получить предмет одежды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета одежды",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/clothes.ClotheUserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/index": {
            "get": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Получает текущее значение индекса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Получить текущий индекс",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/indexer.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Увеличивает значение индекса на 1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Увеличить индекс",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/indexer.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/index/add": {
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Добавляет указанное число к текущему значению индекса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Добавить к индексу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Число для добавления",
                        "name": "number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/indexer.AddToIndexResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/indexer.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/indexer.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/index/double": {
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Удваивает текущее значение индекса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Удвоить индекс",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/indexer.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/indexer.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Получает информацию о текущем пользователе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Создает нового пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Создать пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserRepo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/tap": {
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Выполняет действие тапа для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Тап пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workers/army": {
            "get": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Получает список доступных воинов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workers"
                ],
                "summary": "Получить армию",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workers.UserWorkerResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workers/buy/{id}": {
            "post": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Покупает или улучшает работника",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workers"
                ],
                "summary": "Купить работника",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID работника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workers.UserWorkerResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workers/worker": {
            "get": {
                "security": [
                    {
                        "TelegramAuth": []
                    }
                ],
                "description": "Получает список доступных работников",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workers"
                ],
                "summary": "Получить список работников",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workers.UserWorkerResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "clothes.ClotheUserResponse": {
            "type": "object",
            "properties": {
                "can_buy": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_bought": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "per_for_tap": {
                    "type": "integer"
                },
                "plus_energy": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "rarity": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url_image": {
                    "type": "string"
                }
            }
        },
        "indexer.AddToIndexResponse": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "integer"
                },
                "new_value": {
                    "type": "integer"
                },
                "old_value": {
                    "type": "integer"
                }
            }
        },
        "indexer.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "user.UserRepo": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "body": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "foot": {
                    "type": "string"
                },
                "hand": {
                    "type": "string"
                },
                "head": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_profit_per_hour": {
                    "type": "string"
                },
                "last_restoration": {
                    "type": "string"
                },
                "legs": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "max_energy": {
                    "type": "integer"
                },
                "profit_for_tap": {
                    "type": "integer"
                },
                "profit_per_hour": {
                    "type": "integer"
                },
                "tg_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UserResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "body": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "foot": {
                    "type": "string"
                },
                "hand": {
                    "type": "string"
                },
                "head": {
                    "type": "string"
                },
                "legs": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "max_energy": {
                    "type": "integer"
                },
                "profit_for_tap": {
                    "type": "integer"
                },
                "profit_per_hour": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "workers.UserWorkerResponse": {
            "type": "object",
            "properties": {
                "access_to_upgrade": {
                    "type": "boolean"
                },
                "cost": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "profit": {
                    "type": "integer"
                },
                "url_image": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "TelegramAuth": {
            "description": "Данные инициализации Telegram WebApp",
            "type": "apiKey",
            "name": "X-Telegram-Init-Data",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Documentation",
	Description:      "API сервер для управления пользователями, работниками и одеждой",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,

}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
